//PINS
#define PIN_LEDSTRIP_LEFT 17  
#define PIN_LEDSTRIP_RIGHT 16  
#define PIN_LANESENSOR0 2
#define PIN_LANESENSOR1 3
#define PIN_LANESENSOR2 4
#define PIN_LANESENSOR3 5
#define PIN_LANESENSOR4 6
#define PIN_LANESENSOR5 7
#define PIN_LANESENSOR6 8

//BOARD TYPES
#define BOARDTYPE_REGULAR_ICE 1
#define BOARDTYPE_3ZONES 2

//SCORE GATE
#define SCOREGATE_GREEN 1
#define SCOREGATE_BLUE 2
#define SCOREGATE_PURPLE 3
#define SCOREGATE_RED 4

//DEFINES
#define LEDSTRIP_LENGTH 60
#define LANESENSOR0_OFFSET_IN_LEDS 17
#define LANESENSORS_NO_OF_LEDS 6

#define UNDEFINED -1